Dev
gh-ai-solu/terraform-aws-ccl-apprunner pull request #1
Opened 2021-07-12 20:30 UTC by MaiCabrera

- Setup for basic apprunner

2021-07-14 19:58 UTC, GH-CharlesLandau requested changes

2021-07-14 19:58 UTC, GH-CharlesLandau commented on main.tf
> +    }
You can get rid of this

2021-07-14 19:58 UTC, GH-CharlesLandau commented on main.tf
> +        value = "main"
I thought we were using `image_repository`?

2021-07-14 19:58 UTC, GH-CharlesLandau commented on main.tf
> +    }
We talked about this and you're going to go figure out whether we need to put our existing HCL in a code_configuration repo or if we can get away with just pushing commands to an image_configuration

2021-07-15 18:02 UTC, MaiCabrera commented on main.tf
> +        value = "main"
[Apprunner docs](https://github.com/awsdocs/aws-app-runner-developer-guide/blob/main/doc_source/config-file.md)

source code is the only method that will enable configurations. We can use ECR however we would forego all our config we currently have for the vault

2021-07-15 18:03 UTC, MaiCabrera commented on main.tf
> +    }
code_configuration will be the way to go, link https://github.com/awsdocs/aws-app-runner-developer-guide/blob/main/doc_source/config-file.md

2021-07-15 18:03 UTC, MaiCabrera commented on main.tf
> +  service_arn = aws_apprunner_service.var.service_arn
thank you for the correction in syntax.

2021-07-16 20:15 UTC, GH-CharlesLandau requested changes

2021-07-20 16:45 UTC, MaiCabrera commented on main.tf
> +  service_arn = aws_apprunner_service.service_arn
updated and changed in new commit.

2021-07-20 16:45 UTC, MaiCabrera commented on variables.tf
> +  }))
It didn't and I realized I was majorly messing up this section.

2021-07-20 17:53 UTC, GH-CharlesLandau requested changes

2021-07-20 17:53 UTC, GH-CharlesLandau commented on main.tf
> +    Name = "${var.tags}"
Incorrect, better to do `tags = var.tags` or something with the `merge` builtin function for all of these values. Have a look at how cloudposse does it

2021-07-20 17:53 UTC, GH-CharlesLandau commented on main.tf
> +    Name = "${var.tags}"
See comment above

2021-07-20 17:53 UTC, GH-CharlesLandau commented on main.tf
> +  provider_type   = "${var.provider_type}"
String interpolation again

2021-07-20 17:53 UTC, GH-CharlesLandau commented on main.tf
> +  auto_scaling_configuration_arn = "${aws_apprunner_auto_scaling_configuration_version.dev_apprunner.arn}"
String interpolation in this style is deprecated

2021-07-20 17:53 UTC, GH-CharlesLandau commented on main.tf
> +//ARN IN REQUEST IS THE CONNECTION RESOURCES, IN DOUBT CHECK
Huh? Please explain

2021-07-20 17:53 UTC, GH-CharlesLandau commented on main.tf
> +      connection_arn = "${aws_apprunner_connection.dev_apprunner.arn}"
String interpolation

2021-07-20 17:53 UTC, GH-CharlesLandau commented on main.tf
> +      auto_deployment = "${var.auto_deployment}"
String interpolation. I'm going to stop making this comment but suffice to say please fix this throughout the PR

2021-07-20 17:53 UTC, GH-CharlesLandau commented on main.tf
> +      }
Let's remove `code_configuration_values` and make them always use `REPOSITORY`

2021-07-20 17:53 UTC, GH-CharlesLandau commented on main.tf
> +    kms_key = "${var.kms_key}"
By default, the KMS key should be created as a resource within this module, and then let the user provide a bool variable if they want to use their own, and then if that bool is true then don't create the resource.

2021-07-20 17:53 UTC, GH-CharlesLandau commented on main.tf
> +    instance_role_arn = "${var.instance_role_arn}"
Nope! This needs to be created

2021-07-20 17:53 UTC, GH-CharlesLandau commented on main.tf
>    }
hardcoded tags no no

2021-07-20 17:53 UTC, GH-CharlesLandau commented on output.tf
>  output "arn" {
`arn` is not sufficiently descriptive

2021-07-20 17:53 UTC, GH-CharlesLandau commented on output.tf
> +  value = "${aws_apprunner_auto_scaling_configuration_version.dev_apprunner.arn}"
Why not return the whole resource instead of just the arn?

2021-07-20 17:53 UTC, GH-CharlesLandau commented on output.tf
>  }
Why not collapse this and the previous output into one and return the whole resource?

2021-07-20 17:53 UTC, GH-CharlesLandau commented on output.tf
>  }
Maybe we shouldn't do this? Terraform will read state every time

2021-07-20 17:53 UTC, GH-CharlesLandau commented on output.tf
>  }
What is this?

2021-07-20 17:53 UTC, GH-CharlesLandau commented on output.tf
> +  value = "${aws_apprunner_connection.dev_apprunner.arn}"
Duplicative

2021-07-20 17:53 UTC, GH-CharlesLandau commented on output.tf
> +output "id" {
Vauge

2021-07-20 17:53 UTC, GH-CharlesLandau commented on output.tf
> +}
What is this?

2021-07-20 17:53 UTC, GH-CharlesLandau commented on output.tf
> +}
Duplicative

2021-07-20 17:53 UTC, GH-CharlesLandau commented on output.tf
> +}
Duplicative

2021-07-20 17:53 UTC, GH-CharlesLandau commented on provider.tf
> +
To be removed

2021-07-20 17:53 UTC, GH-CharlesLandau commented on provider.tf
> +}
If you don't drill values from the `variables.tf` file down into the submodules then they won't propagate into the actual `terraform plan`

2021-07-20 17:53 UTC, GH-CharlesLandau commented on variables.tf
>  variable "autoScalingConfigurationName" {
The rest of the PR review suggests so many changes to this that I think you need to reevaluate and I'm not going to review yet if that's ok

2021-07-21 16:53 UTC, MaiCabrera commented on main.tf
> +  auto_scaling_configuration_name = "${var.autoScalingConfigurationName}"
linted

2021-07-21 16:54 UTC, MaiCabrera commented on main.tf
> +  min_size        = "${var.min_size}"
linted

2021-07-21 16:54 UTC, MaiCabrera commented on main.tf
> +    Name = "${var.tags}"
linted

2021-07-21 16:54 UTC, MaiCabrera commented on output.tf
> +}
T.T

2021-07-21 21:59 UTC, MaiCabrera commented on provider.tf
> +}
solved

2021-07-22 01:23 UTC, GH-CharlesLandau requested changes

2021-07-22 01:23 UTC, GH-CharlesLandau commented on main.tf
> +    Name = "${var.tags_autoscaling_group}"
Still interpolating unnecessarily. 

Still needs to align with our convention for tagging: `tags = var.tags` or something with the `merge` builtin function

2021-07-22 01:23 UTC, GH-CharlesLandau commented on main.tf
> +  }
See previous comment about tagging

2021-07-22 01:23 UTC, GH-CharlesLandau commented on output.tf
> +  description = "ARN of the connection for apprunner located in the connection resource output file"
This seems unclear. What would a user do with this output?

2021-07-22 01:23 UTC, GH-CharlesLandau commented on output.tf
> +  value = aws_apprunner_auto_scaling_configuration_version.dev_apprunner.tags_all
Why are we doing this as opposed to outputting the whole resource?

2021-07-22 01:23 UTC, GH-CharlesLandau commented on output.tf
> +output "dev_apprunner_custdomain_id" {
`dev_apprunner_custom_domain_id` We aren't going to run out of ASCII chars 😉

2021-07-22 01:23 UTC, GH-CharlesLandau commented on output.tf
> +  value = aws_apprunner_custom_domain_association.dev_apprunner.dns_target
Descriptions, plus what will users do with this stuff?

2021-07-22 01:23 UTC, GH-CharlesLandau commented on provider.tf
> +  domain_name = "dev_apprunner_aws"
Won't this result in name collision?

2021-07-22 01:23 UTC, GH-CharlesLandau commented on provider.tf
> +  service_tags      = "dev_aws_vault_apprunner_service_tag"
String interpolation again

If the values are hardcoded why are they part of the interface at all? If you're going to hardcode a variable please also have an explanation about why it belongs in `./modules/apprunner/variables.tf` in the first place

2021-07-22 01:23 UTC, GH-CharlesLandau commented on variables.tf
> -  default     = "aws"
There are still lots of unused vars, see previous comment about hardcoding

2021-07-22 01:23 UTC, GH-CharlesLandau commented on variables.tf
>    description = "small detail of how var is used"
Is this a placeholder string? Pls remove

2021-07-22 01:23 UTC, GH-CharlesLandau commented on variables.tf
> +  type = string
No descriptions

2021-07-22 14:46 UTC, MaiCabrera commented on main.tf
> +    Name = "${var.tags_autoscaling_group}"
oversight on my end to not run the tf fmt.

2021-07-22 14:46 UTC, MaiCabrera commented on main.tf
> +  }
oversight on my end to not run the tf fmt.

2021-07-22 15:28 UTC, MaiCabrera commented on variables.tf
>    description = "small detail of how var is used"
its not a placeholder, its referenced by a resource. I'll add more contexts in the description

2021-07-22 15:29 UTC, MaiCabrera commented on provider.tf
> +  service_tags      = "dev_aws_vault_apprunner_service_tag"
Should not be hardcoded, I've updated so that the interpolation string is removed.

2021-07-22 16:38 UTC, MaiCabrera commented on output.tf
> +  value = aws_apprunner_auto_scaling_configuration_version.dev_apprunner.tags_all
commented this out as its not really leveraged or used anywhere.

2021-07-22 16:40 UTC, MaiCabrera commented on output.tf
> +  description = "ARN of the connection for apprunner located in the connection resource output file"
don't believe its used anywhere in the resources.  Should outputs not utilized be nixed?

2021-07-22 16:41 UTC, MaiCabrera commented on output.tf
> +output "dev_apprunner_custdomain_id" {
thought we get charged a penny for each new char

2021-07-22 16:42 UTC, MaiCabrera commented on provider.tf
> +  domain_name = "dev_apprunner_aws"
will change upon getting all elements ready to work

2021-07-28 18:28 UTC, GH-CharlesLandau requested changes

2021-07-28 18:28 UTC, GH-CharlesLandau commented on main.tf
> +}
Cool

2021-07-28 18:28 UTC, GH-CharlesLandau commented on main.tf
> +  tags = merge(local.apprunner_tags, local.autoscaling_tags)
What about `var.tags`

2021-07-28 18:28 UTC, GH-CharlesLandau commented on main.tf
> +  domain_name = var.domain_name
Random suffix?

2021-07-28 18:28 UTC, GH-CharlesLandau commented on main.tf
> +  service_arn = var.service_arn
Shouldn't this reference `aws_apprunner_service.dev_apprunner.arn`

2021-07-28 18:28 UTC, GH-CharlesLandau commented on main.tf
> +      connection_arn = var.connection_arn
Shouldn't this reference `aws_apprunner_connection.dev_apprunner.arn`

2021-07-28 18:28 UTC, GH-CharlesLandau commented on main.tf
> +  tags = merge(local.apprunner_tags, local.service_tags)
What about var.tags

2021-07-28 18:28 UTC, GH-CharlesLandau commented on main.tf
> +    instance_role_arn = var.instance_role_arn
Per our convo about scoped modules, the instance role should be created in here, scoped to this module, and then outputted so the end user can attach more permissions if desired

2021-07-28 18:28 UTC, GH-CharlesLandau commented on variables.tf
> +}
This breaks our usual convention of using the CCL aws project module as an input to define these things

2021-07-28 18:28 UTC, GH-CharlesLandau commented on variables.tf
>  }
Incorrect, the service arn is generated within the module

2021-07-28 18:28 UTC, GH-CharlesLandau commented on variables.tf
> +
Why is this a required variable? Why is it a variable at all?

2021-07-28 18:28 UTC, GH-CharlesLandau commented on variables.tf
> +variable "value" {
Not descriptive

2021-07-28 19:33 UTC, MaiCabrera commented on main.tf
> +  domain_name = var.domain_name
random suffix added

2021-07-28 19:36 UTC, MaiCabrera commented on main.tf
> +      connection_arn = var.connection_arn
updated connection_arn to ingest attribute + removal of unnecessary var

2021-07-28 19:45 UTC, MaiCabrera commented on variables.tf
> +}
fixed and removed unnecessary var

2021-07-28 20:01 UTC, MaiCabrera commented on variables.tf
> +variable "value" {
removed as type and value been hardcoded

2021-07-28 20:02 UTC, MaiCabrera commented on variables.tf
>  }
fixed

2021-07-29 17:18 UTC, closed without merging